### ISSUE TITLE
Add accent recognition

### ISSUE THREAD

**Issue by liolio6** [dynobo/normcap#111]
Hello, I'm French and in French we have accent
And I think normcap doesn't recognize accented characters
Is it possible to add accent recognition ?

When I try to OCR some text with accented characters like "Désactiver"
<details>
  <summary>normcap throw UnicodeEncodeError</summary>

```15:14:08 - INFO - normcap.normcap - Starting NormCap v0.1.12 ...
Traceback (most recent call last):
  File "/home/lionel/.local/bin/normcap", line 10, in <module>
    sys.exit(run())
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/__main__.py", line 5, in run
    _ = main()
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/normcap.py", line 171, in main
    normcap_data = client_code(capture, normcap_data)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/normcap.py", line 122, in client_code
    result = handler.handle(normcap_data)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/capture_handler.py", line 49, in handle
    return super().handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/abstract_handler.py", line 41, in handle
    return self._next_handler.handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/crop_handler.py", line 44, in handle
    return super().handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/abstract_handler.py", line 41, in handle
    return self._next_handler.handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/enhance_img_handler.py", line 38, in handle
    return super().handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/abstract_handler.py", line 41, in handle
    return self._next_handler.handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/store_handler.py", line 31, in handle
    return super().handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/abstract_handler.py", line 41, in handle
    return self._next_handler.handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/ocr_handler.py", line 45, in handle
    return super().handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/abstract_handler.py", line 41, in handle
    return self._next_handler.handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/magic_handler.py", line 65, in handle
    return super().handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/abstract_handler.py", line 41, in handle
    return self._next_handler.handle(request)
  File "/home/lionel/.local/lib/python3.7/site-packages/normcap/handlers/clipboard_handler.py", line 26, in handle
    pyclip.copy(request.transformed)
  File "/home/lionel/.local/lib/python3.7/site-packages/pyclip/__init__.py", line 35, in copy
    return DEFAULT_CLIPBOARD.copy(*args, **kwargs)
  File "/home/lionel/.local/lib/python3.7/site-packages/pyclip/xclip_clip.py", line 68, in copy
    stdout, stderr = proc.communicate(data)
  File "/usr/lib/python3.7/subprocess.py", line 924, in communicate
    self._stdin_write(input)
  File "/usr/lib/python3.7/subprocess.py", line 873, in _stdin_write
    self.stdin.write(input)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 1: ordinal not in range(128)
```
</details>
<details>
  <summary>I'm running normcap on Debian Buster Cinnamon and below list of tesseract on my system</summary>

tesseract-ocr-eng/stable,stable,now 1:4.00\~git30-7274cfa-1 all  [installé]
tesseract-ocr-fra/stable,stable,now 1:4.00\~git30-7274cfa-1 all  [installé]
tesseract-ocr-osd/stable,stable,now 1:4.00~git30-7274cfa-1 all  [installé, automatique]
tesseract-ocr/stable,now 4.0.0-2 amd64  [installé, automatique]
</details>
<details>
  <summary>normcap version</summary>

$ pip3 install normcap==0.1.12
Requirement already satisfied: normcap==0.1.12 in ./.local/lib/python3.7/site-packages (0.1.12)
Requirement already satisfied: pyscreenshot>=2.3 in ./.local/lib/python3.7/site-packages (from normcap==0.1.12) (3.0)
Requirement already satisfied: tesserocr>=2.4.0 in ./.local/lib/python3.7/site-packages (from normcap==0.1.12) (2.5.1)
Requirement already satisfied: Pillow>=8.2.0 in ./.local/lib/python3.7/site-packages (from normcap==0.1.12) (8.2.0)
Requirement already satisfied: mss>=6.1.0 in ./.local/lib/python3.7/site-packages (from normcap==0.1.12) (6.1.0)
Requirement already satisfied: pyclip>=0.5.4 in ./.local/lib/python3.7/site-packages (from normcap==0.1.12) (0.5.4)
Requirement already satisfied: importlib-resources>=5.1.2 in ./.local/lib/python3.7/site-packages (from normcap==0.1.12) (5.1.2)
Requirement already satisfied: notify-py>=0.3.1 in ./.local/lib/python3.7/site-packages (from normcap==0.1.12) (0.3.2)
Requirement already satisfied: jeepney; python_version > "3.4" and platform_system == "Linux" in ./.local/lib/python3.7/site-packages (from pyscreenshot>=2.3->normcap==0.1.12) (0.6.0)
Requirement already satisfied: entrypoint2 in ./.local/lib/python3.7/site-packages (from pyscreenshot>=2.3->normcap==0.1.12) (0.2.4)
Requirement already satisfied: EasyProcess in ./.local/lib/python3.7/site-packages (from pyscreenshot>=2.3->normcap==0.1.12) (0.3)
Requirement already satisfied: zipp>=0.4; python_version < "3.8" in ./.local/lib/python3.7/site-packages (from importlib-resources>=5.1.2->normcap==0.1.12) (3.4.1)
Requirement already satisfied: loguru in ./.local/lib/python3.7/site-packages (from notify-py>=0.3.1->normcap==0.1.12) (0.5.3)
</details>

**Comment by dynobo** [comment]
Hi @liolio6 
Thanks for reporting this issue an the detailed description! :blush:

That's definitely a bug. From the log it seems like the the text recognition itself went well, but putting the text into the clipboard failed. The cause seems to be unclean implementation of the encoding, which just became obvious because of the accent.

Let me see if I can find a quickfix.

PS: Unrelated to the problem: You started NormCap with the language support, right? E.g. `normcap --language fra+eng` ? Because setting the right language improves detection accuracy a lot.

**Comment by dynobo** [comment]
Fix is released for the python package.

Please update and try again:

```sh
pip3 install normcap==0.1.13
normcap --lang eng+fra
```

If you still experience issues, please feel free to re-open. :-)
