### ISSUE TITLE
Application crashes and refuse to start

### ISSUE THREAD

**Issue by 1lgatto** [dynobo/normcap#128]
## Application has crashed!

`<Traceback (most recent call last):
  File "NormCap.app/Contents/Resources/app/normcap/__main__.py", line 3, in <module>
    from normcap.app import main
  File "NormCap.app/Contents/Resources/app/normcap/app.py", line 13, in <module>
    from normcap import __version__, utils
  File "NormCap.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "NormCap.app/Contents/Resources/app/normcap/utils.py", line 14, in <module>
    import tesserocr  # type: ignore  # pylint: disable=wrong-import-order
  File "NormCap.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: dlopen(/Applications/NormCap.app/Contents/Resources/app_packages/tesserocr.cpython-39-darwin.so, 2): Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Applications/NormCap.app/Contents/Resources/app_packages/liblept.5.dylib
  Reason: image not found>`

**NormCap version - v0.2.3**
**OS - macOS Catalina**

**Comment by dynobo** [comment]
Thank for reporting this, @1lgatto.

The issue is clearly related to the packaging for MacOS: `liblept.5.dylib`, a dependency for NormCap, get's shipped with the prebuild-package, but `libpng16.16.dylib` another dependency for _that_ dependency is not included.

I wonder, if you just have a different version of `libpng` installed, or if it is missing completely. Would you please run the following command and post its output?
 ```
 ls /usr/local/opt/libpng/lib/
 ```
 
If it's just a different version, I'll try to link against that, too. Otherwise I'd have to include this `libpng` into the pre-build package.

**Comment by 1lgatto** [comment]
>Otherwise I'd have to include this `libpng` into the pre-build package.

Definitely.

**Comment by GrpeApple** [comment]
> I wonder, if you just have a different version of `libpng` installed, or if it is missing completely. Would you please run the following command and post its output?
> 
> ```
> ls /usr/local/opt/libpng/lib/
> ```

On a clean MacOS installation, `/usr/local`(or `libpng` in this case) does not exist as far as I know.

**Comment by dynobo** [comment]
Thanks for the infos, @1lgatto and @GrpeApple . I'll try to include `libpng` into the next package.

(Some background: Theoretically, all dependencies should be discovered by the packaging tool [`briefcase`](https://github.com/beeware/briefcase), but it doesn't find all of them. I do my best to [add them manually](https://github.com/dynobo/normcap/blob/4781fe96960addd2fd10c35c8236a7d7c98827ea/build.py#L158), but it's a cumbersome process. I also don't own a Mac, which makes things harder to test for me.)
