### ISSUE TITLE
Arch: Uncaught exception. Quitting NormCap.

### ISSUE THREAD

**Issue by Pamalosebi** [dynobo/normcap#188]
Hi,

I am using Arch Linux with the Xfce Desktop Environment.
And when a screenshot is taken, normcap is crashing:

```
# normcap -vV
15:33:45 - INFO    - normcap.app            - L:41  - Start NormCap v0.2.10
15:33:45 - DEBUG   - normcap.app            - L:42  - CLI command: /usr/bin/normcap -vV
15:33:45 - DEBUG   - normcap.app            - L:43  - QT LibraryPaths: ['/usr/lib/qt/plugins']
15:33:45 - INFO    - normcap.utils          - L:148 - Copy 0 traineddata files to config directory
15:33:45 - DEBUG   - normcap.app            - L:56  - System info:
{  'config_directory': PosixPath('/home/user/.config/normcap'),
   'desktop_environment': <DesktopEnvironment.OTHER: 0>,
   'display_manager': <DisplayManager.X11: 2>,
   'gnome_shell_version': '',
   'is_briefcase_package': False,
   'normcap_version': '0.2.10',
   'platform': 'linux',
   'pyside2_version': '5.15.2.1',
   'qt_version': '5.15.2',
   'screens': {  0: ScreenInfo(is_primary=True,
                               device_pixel_ratio=1.0,
                               geometry=Rect(left=0,
                                             top=0,
                                             right=1920,
                                             bottom=1080),
                               index=0)},
   'tessdata_path': '/usr/share/tessdata/',
   'tesseract_languages': ['eng', 'osd'],
   'tesseract_version': '5.0.1'}
15:33:45 - DEBUG   - normcap.base_window    - L:49  - Create window for screen 0
15:33:45 - DEBUG   - normcap.base_window    - L:248 - Set window for screen 0 to fullscreen
15:33:45 - DEBUG   - normcap.system_tray    - L:21  - Set up tray icon
15:33:51 - DEBUG   - normcap.main_window    - L:179 - Hide 1 window(s)
15:33:51 - INFO    - normcap.main_window    - L:272 - Take screenshot of position (377, 532, 988, 547)
15:33:51 - DEBUG   - normcap.screengrab     - L:88  - Grab screen: ScreenInfo(is_primary=True, device_pixel_ratio=1.0, geometry=Rect(left=0, top=0, right=1920, bottom=1080), index=0)
15:33:51 - DEBUG   - normcap.screengrab     - L:134 - Use capture method: QT by screen
15:33:51 - DEBUG   - normcap.utils          - L:32  - Store debug image in: /tmp/normcap/2022-03-01_15-33-51_139921_raw_qt.png
15:33:51 - DEBUG   - normcap.screengrab     - L:167 - Screen scale factor: 1.0
15:33:51 - DEBUG   - normcap.screengrab     - L:168 - Image devicePixelRatio: 1.0
15:33:51 - DEBUG   - normcap.screengrab     - L:171 - Image crop box rect: (377, 532, 611, 15)
15:33:51 - DEBUG   - normcap.utils          - L:32  - Store debug image in: /tmp/normcap/2022-03-01_15-33-51_225068_cropped.png
15:33:51 - DEBUG   - normcap.main_window    - L:281 - Prepare image for OCR
15:33:51 - INFO    - normcap.enhance        - L:17  - Apply enhancements to image
15:33:51 - DEBUG   - normcap.enhance        - L:92  - Resize screenshot by factor 3.2
15:33:51 - DEBUG   - normcap.utils          - L:32  - Store debug image in: /tmp/normcap/2022-03-01_15-33-51_227147_enlarged.png
15:33:51 - DEBUG   - normcap.utils          - L:32  - Store debug image in: /tmp/normcap/2022-03-01_15-33-51_244768_padded.png
15:33:51 - DEBUG   - normcap.main_window    - L:290 - Perform OCR
15:33:51 - DEBUG   - normcap.ocr            - L:62  - Init tesseract with args: {'path': '/usr/share/tessdata/', 'lang': 'eng', 'oem': 1, 'psm': 1}
15:33:51 - ERROR   - normcap.utils          - L:104 - Uncaught exception! Quitting NormCap!
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/normcap/gui/main_window.py", line 291, in _capture_to_ocr
    self.capture = perform_ocr(
  File "/usr/lib/python3.10/site-packages/normcap/ocr.py", line 63, in __call__
    capture = self.extract(capture)
  File "/usr/lib/python3.10/site-packages/normcap/ocr.py", line 82, in extract
    words = self.tsv_to_list_of_dicts(tsv_data)
  File "/usr/lib/python3.10/site-packages/normcap/ocr.py", line 162, in tsv_to_list_of_dicts
    words[idx][key] = int(value)  # type: ignore # (casting on purpose)
ValueError: invalid literal for int() with base 10: '95,512573'
15:33:51 - ERROR   - normcap.utils          - L:107 - Please open an issue with the output above on https://github.com/dynobo/normcap/issues
```

Am I doing something wrong?

**Comment by Pamalosebi** [comment]
I was too fast and just saw #170.
