### ISSUE TITLE
M1 Apple Chip boot issue

### ISSUE THREAD

**Issue by mrtysn** [dynobo/normcap#220]
NormCap won't start in M1 MacBook Pro. You can see the error below:

```
Traceback (most recent call last):
  File "NormCap.app/Contents/Resources/app/normcap/__main__.py", line 3, in <module>
    from normcap.app import main
  File "NormCap.app/Contents/Resources/app/normcap/app.py", line 15, in <module>
    from normcap.gui import system_info, utils
  File "NormCap.app/Contents/Resources/app/normcap/gui/utils.py", line 30, in <module>
    from normcap.ocr.models import OcrResult
  File "NormCap.app/Contents/Resources/app/normcap/ocr/__init__.py", line 1, in <module>
    from normcap.ocr.recognize import pytesseract, recognize
  File "NormCap.app/Contents/Resources/app/normcap/ocr/recognize.py", line 7, in <module>
    import pytesseract  # type: ignore
  File "NormCap.app/Contents/Resources/app_packages/pytesseract/__init__.py", line 2, in <module>
    from .pytesseract import ALTONotSupported
  File "NormCap.app/Contents/Resources/app_packages/pytesseract/pytesseract.py", line 27, in <module>
    from PIL import Image
  File "NormCap.app/Contents/Resources/app_packages/PIL/Image.py", line 132, in <module>
    from . import _imaging as core
ImportError: dlopen(/Applications/NormCap.app/Contents/Resources/app_packages/PIL/_imaging.cpython-39-darwin.so, 0x0002): tried: '/Applications/NormCap.app/Contents/Resources/app_packages/PIL/_imaging.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```
The important bit is at the end:
`incompatible architecture (have 'x86_64', need 'arm64e'))`

Is there an M1 build and if not, do you have plans for supporting it?

Thank you for the nice app! 🍻

**Comment by deepblue81** [comment]
Do you have the last version of NormCap 0.3.4?
Than you must select the app, cmd+i and active the option "Open with Rosetta" - if it's not active...

**Comment by mrtysn** [comment]
That solved the issue. Thanks!

I hadn't needed to enable Rosetta in the past, thus I had no idea of such a functionality.

**Comment by dynobo** [comment]
M1 architecture is now officially supported! See [this comment](https://github.com/dynobo/normcap/issues/248#issuecomment-1374015987).
