### ISSUE TITLE
ValueError: A distribution name is required.

### ISSUE THREAD

**Issue by ABCMoNa** [dynobo/normcap#221]
Hi,

for me, `normcap` fails with error message 
```
ValueError: A distribution name is required.
```

It was installed using `pip install --user normcap`. 

This is on a fully-updated **Ubuntu 20.04.4 LTS**, using the default Debian package `python3` at version `3.8.2-0ubuntu2`.

```
mona@mona1:~$ normcap 
14:26:39 - ERROR   - normcap.utils          - L:104 - Uncaught exception! Quitting NormCap!
Traceback (most recent call last):
  File "/home/mona/.local/bin/normcap", line 8, in <module>
    sys.exit(main())
  File "/home/mona/.local/lib/python3.8/site-packages/normcap/app.py", line 56, in main
    logger.debug("System info:\n%s", system_info.to_string())
  File "/home/mona/.local/lib/python3.8/site-packages/normcap/system_info.py", line 190, in to_string
    is_briefcase_package=is_briefcase_package(),
  File "/home/mona/.local/lib/python3.8/site-packages/normcap/system_info.py", line 161, in is_briefcase_package
    metadata = importlib_metadata.metadata(app_module)
  File "/home/mona/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 1005, in metadata
    return Distribution.from_name(distribution_name).metadata
  File "/home/mona/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 562, in from_name
    raise ValueError("A distribution name is required.")
ValueError: A distribution name is required.
14:26:39 - ERROR   - normcap.utils          - L:107 - Please open an issue with the output above on https://github.com/dynobo/normcap/issues
```

Auxiliary information:

Pip installation completed without error:
```
mona@mona1:~$ pip install --user normcap
Collecting normcap
  Using cached normcap-0.2.10-py3-none-any.whl (402 kB)
Collecting PySide2<6.0.0,>=5.15.2
  Using cached PySide2-5.15.2.1-5.15.2-cp35.cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl (164.3 MB)
Collecting jeepney<0.8.0,>=0.7.1
  Using cached jeepney-0.7.1-py3-none-any.whl (54 kB)
Collecting tesserocr<3.0.0,>=2.4.0; sys_platform == "linux"
  Using cached tesserocr-2.5.2.tar.gz (57 kB)
Collecting importlib-metadata<5.0.0,>=4.10.0
  Using cached importlib_metadata-4.12.0-py3-none-any.whl (21 kB)
Collecting packaging<22.0,>=21.3
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting importlib-resources<6.0.0,>=5.4.0
  Using cached importlib_resources-5.8.0-py3-none-any.whl (28 kB)
Collecting shiboken2==5.15.2.1
  Using cached shiboken2-5.15.2.1-5.15.2-cp35.cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl (975 kB)
Collecting zipp>=0.5
  Using cached zipp-3.8.1-py3-none-any.whl (5.6 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging<22.0,>=21.3->normcap) (2.4.6)
Building wheels for collected packages: tesserocr
  Building wheel for tesserocr (setup.py) ... done
  Created wheel for tesserocr: filename=tesserocr-2.5.2-cp38-cp38-linux_x86_64.whl size=892733 sha256=2d790e47f44401aca331a66cfddd14508bcacdbe3a2104ed1a496c40ddc3e62d
  Stored in directory: /home/mona/.cache/pip/wheels/37/dc/0b/36772b98dae0f858676602cb16ed393eb3353a4abe7d4bb146
Successfully built tesserocr
Installing collected packages: shiboken2, PySide2, jeepney, tesserocr, zipp, importlib-metadata, packaging, importlib-resources, normcap
Successfully installed PySide2-5.15.2.1 importlib-metadata-4.12.0 importlib-resources-5.8.0 jeepney-0.7.1 normcap-0.2.10 packaging-21.3 shiboken2-5.15.2.1 tesserocr-2.5.2 zipp-3.8.1
mona@mona1:~$ 
```

```
mona@mona1:~$ lsb_release -ds
Ubuntu 20.04.4 LTS
```

```
mona@mona1:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

On a side note, please add package `g++` (or the less specific `build-essential`) to the list of requirements on Ubuntu / Debian.

Thanks!

**Comment by ABCMoNa** [comment]
On another side note, the v0.3.4 AppImage build works fine for me on this computer.

**Comment by ABCMoNa** [comment]
I should probably have checked which version pip installed:

``` 
mona@mona1:~$ pip show normcap
Name: normcap
Version: 0.2.10
Summary: OCR-powered screen-capture tool to capture information instead of images.
Home-page: https://github.com/dynobo/normcap
Author: dynobo
Author-email: dynobo@mailbox.org
License: GPLv3
Location: /home/mona/.local/lib/python3.8/site-packages
Requires: PySide2, importlib-resources, jeepney, importlib-metadata, tesserocr, packaging
Required-by: 
mona@mona1:~$ 
```

Are pip installations still supported? Should I be using a different release channel?

**Comment by dynobo** [comment]
Hi @ABCMoNa , thanks for reporting this issue! Yes, the Python packages from pypi still should be maintained.
As seen [on the release history](https://pypi.org/project/normcap/#history), newer version have been uploaded, the fact that `pip install normcap` installs an older version for you indicates, that one of the requirements are not met on your system for newer version.

Looking at your logs, it seems like you are using Python 3.8, while the newer NormCap versionß require >=3.9. 

So you have to install 3.9, e.g. using [pyenv](https://github.com/pyenv/pyenv). I _think_ Ubuntu also provides system packages for other Python versions, so might also be able to do something like:

```sh
sudo apt-get install python3.9
python3.9 -m pip install normcap
```

I'll keep this issue open as a reminder for me to document this requirement. Currently it is only documented for the development setup, not for the package install.

**Comment by ABCMoNa** [comment]
Thank you! Indeed, Python 3.8 here, and I did not realize that's what's causing the older release, whoops.

Thanks for documenting this requirement (and maybe also the other I mentioned as a side note above).
________________________________
