### ISSUE TITLE
Latest version crashes with "TypeError: '<' not supported between instances of 'NoneType' and 'Version'"

### ISSUE THREAD

**Issue by pizzadude** [dynobo/normcap#235]
```
flatpak run com.github.dynobo.normcap -v debug                                                                                                    1  
Traceback (most recent call last):
  File "/app/bin/normcap", line 5, in <module>
    from normcap.app import main
  File "/app/lib/python3.9/site-packages/normcap/app.py", line 14, in <module>
    from normcap.gui import system_info, utils
  File "/app/lib/python3.9/site-packages/normcap/gui/system_info.py", line 15, in <module>
    from normcap.screengrab import get_gnome_version
  File "/app/lib/python3.9/site-packages/normcap/screengrab/__init__.py", line 26, in <module>
    grab_screens = _get_appropriate_grab_screens()
  File "/app/lib/python3.9/site-packages/normcap/screengrab/__init__.py", line 11, in _get_appropriate_grab_screens
    if is_wayland and gnome_version < version.parse("41"):
TypeError: '<' not supported between instances of 'NoneType' and 'Version'

```

This is on Fedora KDE wayland.

**Comment by dynobo** [comment]
Oh, my bad, fix is coming!
