### ISSUE TITLE
ERROR - normcap.utils - L:104 - Uncaught exception! Quitting NormCap!

### ISSUE THREAD

**Issue by blueray453** [dynobo/normcap#241]
```
12:09:57 - ERROR   - normcap.utils          - L:104 - Uncaught exception! Quitting NormCap!
Traceback (most recent call last):
  File "/home/ismail/.local/bin/normcap", line 8, in <module>
    sys.exit(main())
  File "/home/ismail/.local/lib/python3.8/site-packages/normcap/app.py", line 56, in main
    logger.debug("System info:\n%s", system_info.to_string())
  File "/home/ismail/.local/lib/python3.8/site-packages/normcap/system_info.py", line 190, in to_string
    is_briefcase_package=is_briefcase_package(),
  File "/home/ismail/.local/lib/python3.8/site-packages/normcap/system_info.py", line 161, in is_briefcase_package
    metadata = importlib_metadata.metadata(app_module)
  File "/home/ismail/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 1005, in metadata
    return Distribution.from_name(distribution_name).metadata
  File "/home/ismail/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 562, in from_name
    raise ValueError("A distribution name is required.")
ValueError: A distribution name is required.
12:09:57 - ERROR   - normcap.utils          - L:107 - Please open an issue with the output above on https://github.com/dynobo/normcap/issues
```

**Comment by dynobo** [comment]
Hi @blueray453 , thanks for reporting your issue. It seem like you installed NormCap via `pip install` and in an environment with `Python 3.9`? As mention in the [README](https://github.com/dynobo/normcap/blob/main/README.md#python-package), the Python package requires at least Python 3.**9**.

You could try install a newer Python version (e.g. using pyenv) or try the AppImage release.

Does this help you?

**Comment by blueray453** [comment]
Thank you very much.
