### ISSUE TITLE
Crashes on Mac M1 arm64 architecture

### ISSUE THREAD

**Issue by lcalder** [dynobo/normcap#242]
Is it possible to make an ARM64 version for Mac m1?
This is the error I receive when trying to run it:

Traceback (most recent call last):
  File "NormCap.app/Contents/Resources/app/normcap/__main__.py", line 3, in <module>
    from normcap.app import main
  File "NormCap.app/Contents/Resources/app/normcap/app.py", line 14, in <module>
    from normcap.gui import system_info, utils
  File "NormCap.app/Contents/Resources/app/normcap/gui/utils.py", line 29, in <module>
    from normcap.ocr.models import OcrResult
  File "NormCap.app/Contents/Resources/app/normcap/ocr/__init__.py", line 1, in <module>
    from normcap.ocr.recognize import pytesseract, recognize
  File "NormCap.app/Contents/Resources/app/normcap/ocr/recognize.py", line 7, in <module>
    import pytesseract  # type: ignore
  File "NormCap.app/Contents/Resources/app_packages/pytesseract/__init__.py", line 2, in <module>
    from .pytesseract import ALTONotSupported
  File "NormCap.app/Contents/Resources/app_packages/pytesseract/pytesseract.py", line 27, in <module>
    from PIL import Image
  File "NormCap.app/Contents/Resources/app_packages/PIL/Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: dlopen(/Applications/NormCap.app/Contents/Resources/app_packages/PIL/_imaging.cpython-310-darwin.so, 0x0002): tried: '/Applications/NormCap.app/Contents/Resources/app_packages/PIL/_imaging.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

**Comment by dynobo** [comment]
Hi @lcalder, thanks for posting this issue!

Unfortunately, no builds are available for M1 / ARM64 and this probably won't change in the foreseeable future. The only option for users on the architecture is [the installation as Python package](https://dynobo.github.io/normcap/#python-package).

Background: I can't build on ARM64, because [there are no GitHub Runners with that architecture](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) available at the moment. Additionally, I have no M1 myself, so I would be unable to test or debug potential errors.

PS: To avoid others running into the same problem, I should probably add the architecture to the file name (e.g. `NormCap-0.3.7-x86_64-MacOS.dmg`). I'll keep this ticket open as a reminder for me to do that.

**Comment by Stevan-Dinu** [comment]
Also, my M1 is crashing
Traceback (most recent call last):
  File "NormCap.app/Contents/Resources/app/normcap/__main__.py", line 3, in <module>
    from normcap.app import main
  File "NormCap.app/Contents/Resources/app/normcap/app.py", line 14, in <module>
    from normcap.gui import system_info, utils
  File "NormCap.app/Contents/Resources/app/normcap/gui/utils.py", line 29, in <module>
    from normcap.ocr.models import OcrResult
  File "NormCap.app/Contents/Resources/app/normcap/ocr/__init__.py", line 1, in <module>
    from normcap.ocr.recognize import pytesseract, recognize
  File "NormCap.app/Contents/Resources/app/normcap/ocr/recognize.py", line 7, in <module>
    import pytesseract  # type: ignore
  File "NormCap.app/Contents/Resources/app_packages/pytesseract/__init__.py", line 2, in <module>
    from .pytesseract import ALTONotSupported
  File "NormCap.app/Contents/Resources/app_packages/pytesseract/pytesseract.py", line 27, in <module>
    from PIL import Image
  File "NormCap.app/Contents/Resources/app_packages/PIL/Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: dlopen(/Applications/NormCap.app/Contents/Resources/app_packages/PIL/_imaging.cpython-310-darwin.so, 0x0002): tried: '/Applications/NormCap.app/Contents/Resources/app_packages/PIL/_imaging.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

**Comment by dynobo** [comment]
@Stevan-Dinu , please read my comment above.

**Comment by dynobo** [comment]
Added to architecture to file name and provided [FAQ entry](https://dynobo.github.io/normcap/#faqs-macos-m1) on the backgrounds.

**Comment by dynobo** [comment]
M1 architecture is now supported! See [this comment](https://github.com/dynobo/normcap/issues/248#issuecomment-1374015987).
