### ISSUE TITLE
Does not start on macOS ARM64

### ISSUE THREAD

**Issue by FellFromTheSky** [dynobo/normcap#248]
The error I get whenever I try to start the application :
Traceback (most recent call last):
  File "NormCap.app/Contents/Resources/app/normcap/__main__.py", line 3, in <module>
    from normcap.app import main
  File "NormCap.app/Contents/Resources/app/normcap/app.py", line 14, in <module>
    from normcap.gui import system_info, utils
  File "NormCap.app/Contents/Resources/app/normcap/gui/utils.py", line 29, in <module>
    from normcap.ocr.models import OcrResult
  File "NormCap.app/Contents/Resources/app/normcap/ocr/__init__.py", line 1, in <module>
    from normcap.ocr.recognize import pytesseract, recognize
  File "NormCap.app/Contents/Resources/app/normcap/ocr/recognize.py", line 7, in <module>
    import pytesseract  # type: ignore
  File "NormCap.app/Contents/Resources/app_packages/pytesseract/__init__.py", line 2, in <module>
    from .pytesseract import ALTONotSupported
  File "NormCap.app/Contents/Resources/app_packages/pytesseract/pytesseract.py", line 27, in <module>
    from PIL import Image
  File "NormCap.app/Contents/Resources/app_packages/PIL/Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: dlopen(/Applications/NormCap.app/Contents/Resources/app_packages/PIL/_imaging.cpython-310-darwin.so, 0x0002): tried: '/Applications/NormCap.app/Contents/Resources/app_packages/PIL/_imaging.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

**Comment by FellFromTheSky** [comment]
and of course my python3 version is arm64

**Comment by dynobo** [comment]
Hi @FellFromTheSky , please check [FAQ - Does NormCap work on the M1 architecture?](https://dynobo.github.io/normcap/#faqs-macos-m1). Does this answer your questions?

**Comment by FellFromTheSky** [comment]
Yes, thanks a lot.

**Comment by dynobo** [comment]
**Update:**
 
With @Takrin I found a trustworthy contributor who signed up for building packages for M1 manually! 
Please feel free to download the **`arm64`** build for `macOS` from the [latest releases](https://github.com/dynobo/normcap/releases), until GitHub actions support a [runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) with that architecture.
Thanks, @Takrin!
