### ISSUE TITLE
[Linux] "ValueError: A distribution name is required" after installing on pip on Kubuntu

### ISSUE THREAD

**Issue by tavit111** [dynobo/normcap#293]
After running normcap in command line I get the following error:

5:23:59` - ERROR   - normcap.utils          - L:104 - Uncaught exception! Quitting NormCap!
Traceback (most recent call last):
  File "/home/tavit/.local/bin/normcap", line 8, in <module>
    sys.exit(main())
  File "/home/tavit/.local/lib/python3.8/site-packages/normcap/app.py", line 56, in main
    logger.debug("System info:\n%s", system_info.to_string())
  File "/home/tavit/.local/lib/python3.8/site-packages/normcap/system_info.py", line 190, in to_string
    is_briefcase_package=is_briefcase_package(),
  File "/home/tavit/.local/lib/python3.8/site-packages/normcap/system_info.py", line 161, in is_briefcase_package
    metadata = importlib_metadata.metadata(app_module)
  File "/home/tavit/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 1011, in metadata
    return Distribution.from_name(distribution_name).metadata
  File "/home/tavit/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 567, in from_name
    raise ValueError("A distribution name is required.")
ValueError: A distribution name is required.

It seem to work after I commented line responsible for exception.

![](https://user-images.githubusercontent.com/32822588/197341808-fedf0538-4788-409b-9b5a-2e98752367c2.png)

**Comment by tavit111** [comment]
After running normcap in command line I get the following error:

`15:23:59 - ERROR   - normcap.utils          - L:104 - Uncaught exception! Quitting NormCap!
Traceback (most recent call last):
  File "/home/tavit/.local/bin/normcap", line 8, in <module>
    sys.exit(main())
  File "/home/tavit/.local/lib/python3.8/site-packages/normcap/app.py", line 56, in main
    logger.debug("System info:\n%s", system_info.to_string())
  File "/home/tavit/.local/lib/python3.8/site-packages/normcap/system_info.py", line 190, in to_string
    is_briefcase_package=is_briefcase_package(),
  File "/home/tavit/.local/lib/python3.8/site-packages/normcap/system_info.py", line 161, in is_briefcase_package
    metadata = importlib_metadata.metadata(app_module)
  File "/home/tavit/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 1011, in metadata
    return Distribution.from_name(distribution_name).metadata
  File "/home/tavit/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 567, in from_name
    raise ValueError("A distribution name is required.")
ValueError: A distribution name is required.
15:23:59 - ERROR   - normcap.utils          - L:107 - Please open an issue with the output above on https://github.com/dynobo/normcap/issues
`
It seem to work after I commented line responsible for exception.
 
![Screenshot_20221022_152958](https://user-images.githubusercontent.com/32822588/197341808-fedf0538-4788-409b-9b5a-2e98752367c2.png)

**Comment by dynobo** [comment]
Hi @tavit111, it seems like you are using Python 3.8, while the current version of NormCap requires Python >=3.9. 
Probably `pip` installed an older version, which doesn't work anymore on your system. 

You should be able to confirm this by running `pip list | grep normcap`. 

If that's the case, I'd recommend using the [latest AppImage](https://github.com/dynobo/normcap/releases), but you could also try to install Python 3.9. 

Does this help you?

**Comment by dynobo** [comment]
Closing due to inactivity. Please feel free to open, if the issue persists!
