### ISSUE TITLE
ValueError: A distribution name is required.

### ISSUE THREAD

**Issue by YurySams** [dynobo/normcap#495]
### What happened?

run normcamp on Ubuntu

### How did you install NormCap?

Python Package (pip install)

### [Linux only] Display Server (DS) + Desktop environment (DE)?

xorg

### Debug log output?

```shell
00:58:28 - ERROR   - normcap.utils          - L:104 - Uncaught exception! Quitting NormCap!
Traceback (most recent call last):
  File "/home/vahf2ar/.local/bin/normcap", line 8, in <module>
    sys.exit(main())
  File "/home/vahf2ar/.local/lib/python3.8/site-packages/normcap/app.py", line 56, in main
    logger.debug("System info:\n%s", system_info.to_string())
  File "/home/vahf2ar/.local/lib/python3.8/site-packages/normcap/system_info.py", line 190, in to_string
    is_briefcase_package=is_briefcase_package(),
  File "/home/vahf2ar/.local/lib/python3.8/site-packages/normcap/system_info.py", line 161, in is_briefcase_package
    metadata = importlib_metadata.metadata(app_module)
  File "/home/vahf2ar/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 1010, in metadata
    return Distribution.from_name(distribution_name).metadata
  File "/home/vahf2ar/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 567, in from_name
    raise ValueError("A distribution name is required.")
ValueError: A distribution name is required.
00:58:28 - ERROR   - normcap.utils          - L:107 - Please open an issue with the output above on https://github.com/dynobo/normcap/issues
```

**Comment by dynobo** [comment]
@YurySams , thanks for reporting this issue.

From the logs, it seems like you are using Python 3.8, while NormCap moved on to Python 3.9 quite a while ago. So you are either using a quite outdated and therefore potentially broken version (check via `normcap --version` or `pip list | grep normcap`) _or_ you try to run a recent version with an incompatible Python version.

I'd recommend to install NormCap in a separate Python environment with 3.9+, or to give the latest [AppImage release](https://github.com/dynobo/normcap/releases) a try.

In general, please take a look at [the guide to install NormCap as Python package](https://github.com/dynobo/normcap#install-python-package), it should describe all per-requisites and required dependencies.

Does this help you?

**Comment by YurySams** [comment]
Hello, 
No, It doesn't help. 
Unfortunately, I have same issue with same log with python 3.10

Best,
