### ISSUE TITLE
The application crashes on startup.

### ISSUE THREAD

**Issue by Zero0155** [dynobo/normcap#608]
### What happened?

When you try to launch an application, its window appears for a split second and immediately disappears.

### How did you install NormCap?

MSI installer (Windows)

### Operating System + Version?

Windows 10

### Debug log output?*

```shell
PreInitializing Python runtime...
PythonHome: C:\Users\▐Ёшщ ╨ сшэ\AppData\Local\Programs\NormCap
PYTHONPATH:
- C:\Users\▐Ёшщ ╨ сшэ\AppData\Local\Programs\NormCap\python310.zip
- C:\Users\▐Ёшщ ╨ сшэ\AppData\Local\Programs\NormCap
- C:\Users\▐Ёшщ ╨ сшэ\AppData\Local\Programs\NormCap\app_packages
- C:\Users\▐Ёшщ ╨ сшэ\AppData\Local\Programs\NormCap\app
Configure argc/argv...
Initializing Python runtime...
Running app module: normcap
---------------------------------------------------------------------------
18:23:13 - INFO    - normcap:49 - Start NormCap v0.5.4
18:23:13 - DEBUG   - normcap.gui.tray:77 - System info:
{'normcap_version': '0.5.4', 'python_version': '3.10.11', 'cli_args': 'C:\\Users\\╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜\\AppData\\Local\\Programs\\NormCap\\NormCap.exe -v debug', 'is_briefcase_package': True, 'is_flatpak_package': False, 'is_appimage_package': False, 'platform': 'win32', 'desktop_environment': <DesktopEnvironment.OTHER: 0>, 'display_manager_is_wayland': False, 'pyside6_version': '6.6.1', 'qt_version': '6.6.1', 'qt_library_path': 'C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/Programs/NormCap/app_packages/PySide6/plugins, C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/Programs/NormCap', 'locale': 'DEFAULT', 'config_directory': WindowsPath('C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/normcap'), 'resources_path': WindowsPath('C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/Programs/NormCap/app/normcap/resources'), 'tesseract_path': WindowsPath('C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/Programs/NormCap/app/normcap/resources/tesseract/tesseract.exe'), 'tessdata_path': WindowsPath('C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/normcap/tessdata'), 'envs': {'TESSDATA_PREFIX': None, 'LD_LIBRARY_PATH': None}, 'screens': [Screen(left=0, top=0, right=2559, bottom=1439, device_pixel_ratio=1.0, index=0, screenshot=None)]}
18:23:13 - DEBUG   - normcap.gui.settings:162 - Skip update of non existing setting (show_introduction: None)
18:23:13 - DEBUG   - normcap.gui.settings:162 - Skip update of non existing setting (cli_mode: False)
18:23:13 - DEBUG   - normcap.gui.settings:162 - Skip update of non existing setting (background_mode: False)
18:23:13 - DEBUG   - normcap.gui.settings:162 - Skip update of non existing setting (clipboard_handler: None)
18:23:13 - DEBUG   - normcap.gui.tray:388 - Listen on local socket v0.5.4-normcap.
18:23:13 - DEBUG   - normcap.ocr.tesseract:24 - Executing 'C:\Users\╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜\AppData\Local\Programs\NormCap\app\normcap\resources\tesseract\tesseract.exe --list-langs --tessdata-dir C:\Users\╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜\AppData\Local\normcap\tessdata'
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "subprocess.py", line 1515, in _readerthread
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 41: invalid continuation byte
18:23:13 - CRITICAL - normcap:148 - Uncaught exception!
Traceback (most recent call last):
  File "C:\Users\╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜\AppData\Local\Programs\NormCap\app\normcap\gui\tray.py", line 368, in _delayed_init    self.installed_languages = ocr.tesseract.get_languages(
  File "C:\Users\╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜\AppData\Local\Programs\NormCap\app\normcap\ocr\tesseract.py", line 52, in get_languages
    output = _run_command(cmd_args=cmd_args)
  File "C:\Users\╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜\AppData\Local\Programs\NormCap\app\normcap\ocr\tesseract.py", line 38, in _run_command
    "Tesseract command output: %s", out_str.replace(linesep, " ┬м ").strip()
AttributeError: 'NoneType' object has no attribute 'replace'
18:23:13 - CRITICAL - normcap:151 - System info: {'normcap_version': '0.5.4', 'python_version': '3.10.11', 'cli_args': 'C:\\Users\\╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜\\AppData\\Local\\Programs\\NormCap\\NormCap.exe -v debug', 'is_briefcase_package': True, 'is_flatpak_package': False, 'is_appimage_package': False, 'platform': 'win32', 'desktop_environment': <DesktopEnvironment.OTHER: 0>, 'display_manager_is_wayland': False, 'pyside6_version': '6.6.1', 'qt_version': '6.6.1', 'qt_library_path': 'C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/Programs/NormCap/app_packages/PySide6/plugins, C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/Programs/NormCap', 'locale': 'DEFAULT', 'config_directory': WindowsPath('C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/normcap'), 'resources_path': WindowsPath('C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/Programs/NormCap/app/normcap/resources'), 'tesseract_path': WindowsPath('C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/Programs/NormCap/app/normcap/resources/tesseract/tesseract.exe'), 'tessdata_path': WindowsPath('C:/Users/╨о╤А╨╕╨╣ ╨а╤П╨▒╨╕╨╜/AppData/Local/normcap/tessdata'), 'envs': {'TESSDATA_PREFIX': None, 'LD_LIBRARY_PATH': None}, 'screens': [Screen(left=0, top=0, right=2559, bottom=1439, device_pixel_ratio=1.0, index=0, screenshot=None)]}
18:23:13 - CRITICAL - normcap:152 - Unfortunately, NormCap has to be terminated due to an unknown problem.
Please help improve NormCap by reporting this error, including the output above, on
https://github.com/dynobo/normcap/issues/new
Thanks!
```

**Comment by Invisible02** [comment]
I have the same thing happening when I run NormCap installed with MSI installer. I tried to install it from the Microsoft Store, and it didn't even show the main window, but immediately after a few seconds a window with the following error popped up:
```
Traceback (most recent call last):
  File "\app\normcap\__main__.py", line 6, in <module
    main()
  File "\app\normcap\app.py", line 56, in main
    tray = SystemTray(app, vars(args))
  File "\app\normcap\gui\tray.py", line 77, in __init__
    self._sanatize_active_language(self.settings)
  File "\app\normcap\gui\tray.py", line 300, in _sanatize_active_language
    installed_languages = ocr.utils.get_tesseract_languages(
  File "\app\normcap\ocr\utils.py", line 38, in get_tesseract_languages
    pytesseract.get_languages.__wrapped__(
  File "\app_packages\pytesseract\pytesseract.py", line 374, in get_languages
    for line in result.stdout.decode(DEFAULT_ENCODING).split(linesep):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 at position 41: invalid start byte
```

I want to note that the name of my Windows user folder contains only Cyrillic characters. As I understand it, this is the reason.
