### ISSUE TITLE
"NormCap has to be terminated due to an unknown problem" in wayland of KDE6 

### ISSUE THREAD

**Issue by godsbball** [dynobo/normcap#609]
works well in X11,but error occurs in wayland of KDE6:
```
$ NormCap-0.5.4-x86_64.AppImage
19:36:19 - CRITICAL - normcap:148 - Uncaught exception!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.mount_NormCaCEuxAS/usr/python/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/tmp/.mount_NormCaCEuxAS/usr/python/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/tmp/.mount_NormCaCEuxAS/usr/python/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_NormCaCEuxAS/usr/app/normcap/__main__.py", line 6, in <module>
    run()
  File "/tmp/.mount_NormCaCEuxAS/usr/app/normcap/app.py", line 101, in run
    app, tray = _prepare()
  File "/tmp/.mount_NormCaCEuxAS/usr/app/normcap/app.py", line 94, in _prepare
    tray = SystemTray(app, vars(args))
  File "/tmp/.mount_NormCaCEuxAS/usr/app/normcap/gui/tray.py", line 145, in __init__
    self._show_windows(delay_screenshot=delay_screenshot)
  File "/tmp/.mount_NormCaCEuxAS/usr/app/normcap/gui/tray.py", line 208, in _show_windows
    self._create_window(index)
  File "/tmp/.mount_NormCaCEuxAS/usr/app/normcap/gui/tray.py", line 547, in _create_window
    new_window.set_fullscreen()
  File "/tmp/.mount_NormCaCEuxAS/usr/app/normcap/gui/window.py", line 131, in set_fullscreen
    raise ValueError("Screenshot is missing on screen %s", self.screen_)
ValueError: ('Screenshot is missing on screen %s', Screen(left=0, top=0, right=1645, bottom=1028, device_pixel_ratio=2.0, index=0, screenshot=<PySide6.QtGui.QImage(null) at 0x7f0e6493f8c0>))
19:36:19 - CRITICAL - normcap:151 - System info: {'normcap_version': '0.5.4', 'python_version': '3.10.13', 'cli_args': '-c', 'is_briefcase_package': True, 'is_flatpak_package': False, 'is_appimage_package': True, 'platform': 'linux', 'desktop_environment': <DesktopEnvironment.KDE: 2>, 'display_manager_is_wayland': True, 'pyside6_version': '6.6.1', 'qt_version': '6.6.1', 'qt_library_path': '/tmp/.mount_NormCaCEuxAS/usr/app_packages/PySide6/Qt/plugins, /tmp/.mount_NormCaCEuxAS/usr/python/bin', 'locale': 'DEFAULT', 'config_directory': PosixPath('/home/burst/.config/normcap'), 'resources_path': PosixPath('/tmp/.mount_NormCaCEuxAS/usr/app/normcap/resources'), 'tesseract_path': PosixPath('/tmp/.mount_NormCaCEuxAS/usr/bin/tesseract'), 'tessdata_path': PosixPath('/home/burst/.config/normcap/tessdata'), 'envs': {'TESSDATA_PREFIX': None, 'LD_LIBRARY_PATH': None}, 'screens': [Screen(left=0, top=0, right=1645, bottom=1028, device_pixel_ratio=2.0, index=0, screenshot=None)]}
19:36:19 - CRITICAL - normcap:152 - Unfortunately, NormCap has to be terminated due to an unknown problem.

```

**Comment by 5ohue** [comment]
I have same exact issue on KDE6 with wayland

**Comment by arvindchauhan1** [comment]
facing same issue with ubuntu on wayland

**Comment by nivaca** [comment]
Same here.
