### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by vladimiregorov74** [dynobo/normcap#616]
(.venv) vladimir@vladimiregorov74:~/PycharmProjects/Normcap$ python3 -m normcap
21:16:40 - CRITICAL - normcap:148 - Uncaught exception!
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/vladimir/PycharmProjects/Normcap/.venv/lib/python3.10/site-packages/normcap/__main__.py", line 6, in <module>
    run()
  File "/home/vladimir/PycharmProjects/Normcap/.venv/lib/python3.10/site-packages/normcap/app.py", line 101, in run
    app, tray = _prepare()
  File "/home/vladimir/PycharmProjects/Normcap/.venv/lib/python3.10/site-packages/normcap/app.py", line 94, in _prepare
    tray = SystemTray(app, vars(args))
  File "/home/vladimir/PycharmProjects/Normcap/.venv/lib/python3.10/site-packages/normcap/gui/tray.py", line 145, in __init__
    self._show_windows(delay_screenshot=delay_screenshot)
  File "/home/vladimir/PycharmProjects/Normcap/.venv/lib/python3.10/site-packages/normcap/gui/tray.py", line 208, in _show_windows
    self._create_window(index)
  File "/home/vladimir/PycharmProjects/Normcap/.venv/lib/python3.10/site-packages/normcap/gui/tray.py", line 547, in _create_window
    new_window.set_fullscreen()
  File "/home/vladimir/PycharmProjects/Normcap/.venv/lib/python3.10/site-packages/normcap/gui/window.py", line 131, in set_fullscreen
    raise ValueError("Screenshot is missing on screen %s", self.screen_)
ValueError: ('Screenshot is missing on screen %s', Screen(left=0, top=0, right=1919, bottom=1079, device_pixel_ratio=1.0, index=0, screenshot=<PySide6.QtGui.QImage(null) at 0x7c910f00d0c0>))
21:16:40 - CRITICAL - normcap:151 - System info: {'normcap_version': '0.5.4', 'python_version': '3.10.12', 'cli_args': '/home/vladimir/PycharmProjects/Normcap/.venv/lib/python3.10/site-packages/normcap/__main__.py', 'is_briefcase_package': False, 'is_flatpak_package': False, 'is_appimage_package': False, 'platform': 'linux', 'desktop_environment': <DesktopEnvironment.GNOME: 1>, 'display_manager_is_wayland': True, 'pyside6_version': '6.6.1', 'qt_version': '6.6.1', 'qt_library_path': '/home/vladimir/PycharmProjects/Normcap/.venv/lib/python3.10/site-packages/PySide6/Qt/plugins, /usr/bin', 'locale': 'ru_RU', 'config_directory': PosixPath('/home/vladimir/.config/normcap'), 'resources_path': PosixPath('/home/vladimir/PycharmProjects/Normcap/.venv/lib/python3.10/site-packages/normcap/resources'), 'tesseract_path': PosixPath('/usr/bin/tesseract'), 'tessdata_path': None, 'envs': {'TESSDATA_PREFIX': None, 'LD_LIBRARY_PATH': None}, 'screens': [Screen(left=0, top=0, right=1919, bottom=1079, device_pixel_ratio=1.0, index=0, screenshot=None)]}
21:16:40 - CRITICAL - normcap:152 - Unfortunately, NormCap has to be terminated due to an unknown problem.

**Comment by dynobo** [comment]
Hi @vladimiregorov74,
Could you please run NormCap with debug log flag an post that output? In your case:
```sh
python3 -m normcap -v debug
```
