### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by Do-fomin** [dynobo/normcap#645]
### What happened?

Перестало запускаться приложение, переустановка не помогает. При попытке запуска иконка появляется на панели и исчезает через несколько секунд, но само приложение не запускается 
![image](https://github.com/dynobo/normcap/assets/107024858/c987691a-d07b-43a5-89ea-16cc4d685b67)

### How did you install NormCap?

FlatPak (Linux)

### Operating System + Version?

Fedora KDE 40

### [Linux only] Display Server (DS) + Desktop environment (DE)?

KDE Plasma 6

### Debug log output?*

```shell
Cryo@Cryodora:~$ flatpak run --command=normcap com.github.dynobo.normcap -v debug
22:15:29 - INFO    - normcap:50 - Start NormCap v0.5.6
22:15:29 - DEBUG   - normcap:95 - Set XCURSOR_SIZE=24
22:15:29 - DEBUG   - normcap:100 - Set QT_QPA_PLATFORM=wayland
22:15:29 - DEBUG   - normcap.gui.tray:70 - System info:
{'normcap_version': '0.5.6', 'python_version': '3.11.9', 'cli_args': '/app/bin/normcap -v debug', 'is_briefcase_package': False, 'is_flatpak_package': True, 'is_appimage_package': False, 'platform': 'linux', 'desktop_environment': <DesktopEnvironment.KDE: 3>, 'display_manager_is_wayland': True, 'pyside6_version': '6.7.0', 'qt_version': '6.7.0', 'qt_library_path': '/usr/share/runtime/lib/plugins, /app/lib/python3.11/site-packages/PySide6/Qt/plugins, /usr/bin', 'locale': 'ru_RU', 'config_directory': PosixPath('/home/Cryo/.var/app/com.github.dynobo.normcap/config/normcap'), 'resources_path': PosixPath('/app/lib/python3.11/site-packages/normcap/resources'), 'tesseract_path': PosixPath('/app/bin/tesseract'), 'tessdata_path': PosixPath('/home/Cryo/.var/app/com.github.dynobo.normcap/config/normcap/tessdata'), 'envs': {'TESSDATA_PREFIX': '/app/share', 'LD_LIBRARY_PATH': ''}, 'screens': [Screen(left=0, top=0, right=1439, bottom=899, device_pixel_ratio=2.0, index=0, screenshot=None)]}
22:15:29 - DEBUG   - normcap.gui.settings:162 - Skip update of non existing setting (show_introduction: None)
22:15:29 - DEBUG   - normcap.gui.settings:162 - Skip update of non existing setting (cli_mode: False)
22:15:29 - DEBUG   - normcap.gui.settings:162 - Skip update of non existing setting (background_mode: False)
22:15:29 - DEBUG   - normcap.gui.settings:162 - Skip update of non existing setting (clipboard_handler: None)
22:15:29 - DEBUG   - normcap.gui.tray:384 - Listen on local socket v0.5.6-normcap.
22:15:29 - DEBUG   - normcap.screengrab.permissions:222 - Checking screenshot permission
22:15:29 - DEBUG   - normcap.screengrab.handlers.dbus_portal:92 - DBus request message: <PySide6.QtDBus.QDBusMessage(type=MethodReturn, service="", signature="o", contents=([ObjectPath: /org/freedesktop/portal/desktop/request/1_176/normcap_hehhdecd]) ) at 0x7febc971bf40>
22:15:29 - DEBUG   - normcap.screengrab.handlers.dbus_portal:99 - Request accepted
22:15:29 - DEBUG   - normcap.ocr.tesseract:24 - Executing '/app/bin/tesseract --list-langs --tessdata-dir /home/Cryo/.var/app/com.github.dynobo.normcap/config/normcap/tessdata'
22:15:29 - DEBUG   - normcap.ocr.tesseract:37 - Tesseract command output: List of available languages in "/home/Cryo/.var/app/com.github.dynobo.normcap/config/normcap/tessdata/" (1): ¬ eng ¬
22:15:29 - DEBUG   - normcap.screengrab.handlers.dbus_portal:119 - DBus signal message: <PySide6.QtDBus.QDBusMessage(type=Signal, service=":1.28", path="/org/freedesktop/portal/desktop/request/1_176/normcap_hehhdecd", interface="org.freedesktop.portal.Request", member="Response", signature="ua{sv}", contents=(0, [Argument: a{sv} {"uri" = [Variant(QString): "file:///home/Cryo/%D0%98%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F/Screenshot_20240514_221529.png"]}]) ) at 0x7febc9712800>
22:15:29 - DEBUG   - normcap.screengrab.handlers.dbus_portal:137 - Parse response
22:15:29 - CRITICAL - normcap:148 - Uncaught exception!
Traceback (most recent call last):
  File "/app/bin/normcap", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/app/lib/python3.11/site-packages/normcap/app.py", line 102, in run
    app, tray = _prepare()
                ^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/app.py", line 95, in _prepare
    tray = SystemTray(app, vars(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/gui/tray.py", line 111, in __init__
    if not self._ensure_screenshot_permission():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/gui/tray.py", line 402, in _ensure_screenshot_permission
    if screengrab.has_screenshot_permission():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/permissions.py", line 228, in has_screenshot_permission
    return _dbus_portal_has_screenshot_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/permissions.py", line 200, in _dbus_portal_has_screenshot_permission
    result = dbus_portal.capture()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 241, in capture
    image = _synchronized_capture(interactive=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 209, in _synchronized_capture
    image_path.unlink()
  File "/usr/lib/python3.11/pathlib.py", line 1147, in unlink
    os.unlink(self)
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/home/Cryo/%D0%98%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F/Screenshot_20240514_221529.png'
22:15:29 - CRITICAL - normcap:151 - System info: {'normcap_version': '0.5.6', 'python_version': '3.11.9', 'cli_args': '/app/bin/normcap -v debug', 'is_briefcase_package': False, 'is_flatpak_package': True, 'is_appimage_package': False, 'platform': 'linux', 'desktop_environment': <DesktopEnvironment.KDE: 3>, 'display_manager_is_wayland': True, 'pyside6_version': '6.7.0', 'qt_version': '6.7.0', 'qt_library_path': '/usr/share/runtime/lib/plugins, /app/lib/python3.11/site-packages/PySide6/Qt/plugins, /usr/bin', 'locale': 'ru_RU', 'config_directory': PosixPath('/home/Cryo/.var/app/com.github.dynobo.normcap/config/normcap'), 'resources_path': PosixPath('/app/lib/python3.11/site-packages/normcap/resources'), 'tesseract_path': PosixPath('/app/bin/tesseract'), 'tessdata_path': PosixPath('/home/Cryo/.var/app/com.github.dynobo.normcap/config/normcap/tessdata'), 'envs': {'TESSDATA_PREFIX': '/app/share', 'LD_LIBRARY_PATH': ''}, 'screens': [Screen(left=0, top=0, right=1439, bottom=899, device_pixel_ratio=2.0, index=0, screenshot=None)]}
22:15:29 - CRITICAL - normcap:152 - Unfortunately, NormCap has to be terminated due to an unknown problem.
Please help improve NormCap by reporting this error, including the output above, on
https://github.com/dynobo/normcap/issues/new
```

**Comment by dynobo** [comment]
Thanks for reporting! This error is already known (#643) and fixed, but not yet released. Please wait for the next NormCap version which should get published in a few daysn
