### ISSUE TITLE
normcap issue on hyprland

### ISSUE THREAD

**Issue by brahimjarallah** [dynobo/normcap#662]
16:44:42 - ERROR   - normcap.screengrab.handlers.dbus_portal:102 - No object path received from xdg-portal!
16:44:42 - CRITICAL - normcap:148 - Uncaught exception!
Traceback (most recent call last):
  File "/usr/bin/normcap", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/normcap/app.py", line 102, in run
    app, tray = _prepare()
                ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/normcap/app.py", line 95, in _prepare
    tray = SystemTray(app, vars(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/normcap/gui/tray.py", line 111, in __init__
    if not self._ensure_screenshot_permission():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/normcap/gui/tray.py", line 402, in _ensure_screenshot_permission
    if screengrab.has_screenshot_permission():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/normcap/screengrab/permissions.py", line 228, in has_screenshot_permission
    return _dbus_portal_has_screenshot_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/normcap/screengrab/permissions.py", line 200, in _dbus_portal_has_screenshot_permission
    result = dbus_portal.capture()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 242, in capture
    image = _synchronized_capture(interactive=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 198, in _synchronized_capture
    raise error
RuntimeError: No object path received from xdg-portal!
16:44:42 - CRITICAL - normcap:151 - System info: {'normcap_version': '0.5.8', 'python_version': '3.12.5', 'cli_args': '/usr/bin/normcap', 'is_briefcase_package': False, 'is_flatpak_package': False, 'is_appimage_package': False, 'platform': 'linux', 'desktop_environment': <DesktopEnvironment.HYPRLAND: 6>, 'display_manager_is_wayland': True, 'pyside6_version': '6.7.2', 'qt_version': '6.7.2', 'qt_library_path': '/usr/lib/qt6/plugins, /usr/bin', 'locale': 'DEFAULT', 'config_directory': PosixPath('/home/brahim/.config/normcap'), 'resources_path': PosixPath('/usr/lib/python3.12/site-packages/normcap/resources'), 'tesseract_path': PosixPath('/usr/bin/tesseract'), 'tessdata_path': None, 'envs': {'TESSDATA_PREFIX': None, 'LD_LIBRARY_PATH': None}, 'screens': [Screen(left=0, top=0, right=1365, bottom=767, device_pixel_ratio=1.0, index=0, screenshot=None), Screen(left=1366, top=0, right=3285, bottom=1079, device_pixel_ratio=1.0, index=1, screenshot=None)]}
16:44:42 - CRITICAL - normcap:152 - Unfortunately, NormCap has to be terminated due to an unknown problem.
Please help improve NormCap by reporting this error, including the output above, on
https://github.com/dynobo/normcap/issues/new
Thanks!

**Comment by brahimjarallah** [comment]
help please ! to make it work correctly ! :'(

**Comment by bogorad** [comment]
in my case `xdg-portal` was missing :)
