### ISSUE TITLE
normcap not working on Ubuntu 24.10

### ISSUE THREAD

**Issue by Hyphaed** [dynobo/normcap#666]
### What happened?

I'm running normcap from flathub

seems error is related with qt libraries

`(base) ferran@z590i:~/Documents/PersonalPackages/normcap$ flatpak run com.github.dynobo.normcap     
F: Not sharing "/usr/share" with sandbox: Path "/usr" is reserved by Flatpak
F: Not sharing "/usr/share/themes" with sandbox: Path "/usr" is reserved by Flatpak
10:08:10 - ERROR   - normcap.screengrab.handlers.dbus_portal:127 - Permission denied for Screenshot via xdg-portal! Message: <PySide6.QtDBus.QDBusMessage(type=Signal, service=":1.72", path="/org/freedesktop/portal/desktop/request/1_362/normcap_gcfaeefd", interface="org.freedesktop.portal.Request", member="Response", signature="ua{sv}", contents=(2, [Argument: a{sv} {}]) ) at 0x7ba40c466900>
10:08:10 - WARNING - normcap.screengrab.permissions:202 - Screenshot permissions on Wayland seem missing.
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/normcap/screengrab/permissions.py", line 200, in _dbus_portal_has_screenshot_permission
    result = dbus_portal.capture()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 242, in capture
    image = _synchronized_capture(interactive=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 198, in _synchronized_capture
    raise error
PermissionError: Permission denied for Screenshot via xdg-portal! Message: <PySide6.QtDBus.QDBusMessage(type=Signal, service=":1.72", path="/org/freedesktop/portal/desktop/request/1_362/normcap_gcfaeefd", interface="org.freedesktop.portal.Request", member="Response", signature="ua{sv}", contents=(2, [Argument: a{sv} {}]) ) at 0x7ba40c466900>
10:08:12 - ERROR   - normcap:181 - [QT] qtfatalmsg - cannot mix incompatible qt library (6.7.3) with this library (6.7.0)
`

### How did you install NormCap?

None

### Debug log output?*

```shell
`(base) ferran@z590i:~/Documents/PersonalPackages/normcap$ flatpak run com.github.dynobo.normcap     
F: Not sharing "/usr/share" with sandbox: Path "/usr" is reserved by Flatpak
F: Not sharing "/usr/share/themes" with sandbox: Path "/usr" is reserved by Flatpak
10:08:10 - ERROR   - normcap.screengrab.handlers.dbus_portal:127 - Permission denied for Screenshot via xdg-portal! Message: <PySide6.QtDBus.QDBusMessage(type=Signal, service=":1.72", path="/org/freedesktop/portal/desktop/request/1_362/normcap_gcfaeefd", interface="org.freedesktop.portal.Request", member="Response", signature="ua{sv}", contents=(2, [Argument: a{sv} {}]) ) at 0x7ba40c466900>
10:08:10 - WARNING - normcap.screengrab.permissions:202 - Screenshot permissions on Wayland seem missing.
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/normcap/screengrab/permissions.py", line 200, in _dbus_portal_has_screenshot_permission
    result = dbus_portal.capture()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 242, in capture
    image = _synchronized_capture(interactive=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 198, in _synchronized_capture
    raise error
PermissionError: Permission denied for Screenshot via xdg-portal! Message: <PySide6.QtDBus.QDBusMessage(type=Signal, service=":1.72", path="/org/freedesktop/portal/desktop/request/1_362/normcap_gcfaeefd", interface="org.freedesktop.portal.Request", member="Response", signature="ua{sv}", contents=(2, [Argument: a{sv} {}]) ) at 0x7ba40c466900>
10:08:12 - ERROR   - normcap:181 - [QT] qtfatalmsg - cannot mix incompatible qt library (6.7.3) with this library (6.7.0)
`
```

**Comment by cvpsmith** [comment]
Same error.  Can't get AppImage or Flatpak to work on Ububtu 24.10.

**Comment by Hyphaed** [comment]
I've solved it, just don't remember how

It crashes after first screenshot/OCR, yet is enough like this :: if I want a 2nd OCR I open again the app

I needed to install a library, and after I've installed it I got a message on the first run asking for "capturing screen" permission

**Comment by yue-dongchen** [comment]
I'm on Ubuntu 24.04 with the same debug information. The Appimage works though.

**Comment by jasiralavibiztripz** [comment]
AppImage wasn't working when I had flatpak installed as well. I removed both and then downloaded AppImage again. it's working now.

**Comment by dmchmk** [comment]
NixOS user here, with the same issue:

```
$ flatpak run com.github.dynobo.normcap
18:35:31 - ERROR   - normcap.screengrab.handlers.dbus_portal:127 - Permission denied for Screenshot via xdg-portal! Message: <PySide6.QtDBus.QDBusMessage(type=Signal, service=":1.65", path="/org/freedesktop/portal/desktop/request/1_1299/normcap_daggieie", interface="org.freedesktop.portal.Request", member="Response", signature="ua{sv}", contents=(2, [Argument: a{sv} {}]) ) at 0x7f0a8341a240>
18:35:31 - WARNING - normcap.screengrab.permissions:202 - Screenshot permissions on Wayland seem missing.
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/normcap/screengrab/permissions.py", line 200, in _dbus_portal_has_screenshot_permission
    result = dbus_portal.capture()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 242, in capture
    image = _synchronized_capture(interactive=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 198, in _synchronized_capture
    raise error
PermissionError: Permission denied for Screenshot via xdg-portal! Message: <PySide6.QtDBus.QDBusMessage(type=Signal, service=":1.65", path="/org/freedesktop/portal/desktop/request/1_1299/normcap_daggieie", interface="org.freedesktop.portal.Request", member="Response", signature="ua{sv}", contents=(2, [Argument: a{sv} {}]) ) at 0x7f0a8341a240>
18:35:32 - ERROR   - normcap:181 - [QT] qtfatalmsg - cannot mix incompatible qt library (6.7.3) with this library (6.7.1)
```

(ver. 0.5.9)

**Comment by AdnanHodzic** [comment]
Same issue on Ubuntu 25.04 and normcap installed as a Flatpak.

```
flatpak run com.github.dynobo.normcap      
10:26:07 - ERROR   - normcap.screengrab.handlers.dbus_portal:127 - Permission denied for Screenshot via xdg-portal! Message: <PySide6.QtDBus.QDBusMessage(type=Signal, service=":1.86", path="/org/freedesktop/portal/desktop/request/1_432/normcap_hfhfhcba", interface="org.freedesktop.portal.Request", member="Response", signature="ua{sv}", contents=(2, [Argument: a{sv} {}]) ) at 0x728fb081eb80>
10:26:07 - WARNING - normcap.screengrab.permissions:202 - Screenshot permissions on Wayland seem missing.
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/normcap/screengrab/permissions.py", line 200, in _dbus_portal_has_screenshot_permission
    result = dbus_portal.capture()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 242, in capture
    image = _synchronized_capture(interactive=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/normcap/screengrab/handlers/dbus_portal.py", line 198, in _synchronized_capture
    raise error
PermissionError: Permission denied for Screenshot via xdg-portal! Message: <PySide6.QtDBus.QDBusMessage(type=Signal, service=":1.86", path="/org/freedesktop/portal/desktop/request/1_432/normcap_hfhfhcba", interface="org.freedesktop.portal.Request", member="Response", signature="ua{sv}", contents=(2, [Argument: a{sv} {}]) ) at 0x728fb081eb80>
10:26:08 - ERROR   - normcap:181 - [QT] qtfatalmsg - cannot mix incompatible qt library (6.7.3) with this library (6.7.1)
```

**Comment by Hyphaed** [comment]
I see people still with problems, for me now is working :: Only I've done is keep updating my system.

**Comment by dmchmk** [comment]
> Can you try granting the permissions manuall?

do you think it's the proper way how the app should be working on the user-side?

**Comment by dynobo** [comment]
> I literally just installed it today to make those screenshots, because it was uninstalled when I've discovered that it's not working:)

Could you please try again with the new v0.6.0 release? It includes some changes, which should help with automatically requesting the screenshot permissions, at least on some systems.
