### ISSUE TITLE
Error: undefined symbol: wl_display_create_queue_with_name

### ISSUE THREAD

**Issue by M4rt1n12** [dynobo/normcap#667]
### What happened?

I started NormCap-0.5.8-x86_64.appimage from terminal. And got this error:

`/tmp/.mount_NormCawAIcRR/usr/python/bin/python3: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_display_create_queue_with_name
`

### How did you install NormCap?

None

### Operating System + Version?

Debian testing

### [Linux only] Display Server (DS) + Desktop environment (DE)?

Wayland, Plasma 5.27.11

### Debug log output?*

```shell
/tmp/.mount_NormCawAIcRR/usr/python/bin/python3: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_display_create_queue_with_name
```

**Comment by M4rt1n12** [comment]
Everything works fine with an old version: NormCap-0.4.4-x86_64.AppImage

**Comment by M4rt1n12** [comment]
If I install normcap with pip, I get this error:

`22:27:05 - INFO - normcap.normcap - Starting NormCap v0.1.13 ...
Traceback (most recent call last):
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/easyprocess/__init__.py", line 176, in start
    self.popen = subprocess.Popen(
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gnome-screenshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martin/bin/NormCap/bin/normcap", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/normcap/__main__.py", line 5, in run
    _ = main()
        ^^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/normcap/normcap.py", line 171, in main
    normcap_data = client_code(capture, normcap_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/normcap/normcap.py", line 122, in client_code
    result = handler.handle(normcap_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/normcap/handlers/capture_handler.py", line 44, in handle
    request = self._take_screenshot_alternative(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/normcap/handlers/capture_handler.py", line 101, in _take_screenshot_alternative
    img_complete = ImageGrab.grab(backend="gnome-screenshot")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/pyscreenshot/__init__.py", line 37, in grab
    return backend_grab(backend, bbox, childprocess)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/pyscreenshot/loader.py", line 169, in backend_grab
    return force(backend, bbox, childprocess)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/pyscreenshot/loader.py", line 163, in force
    im = obj.grab(bbox)
         ^^^^^^^^^^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/pyscreenshot/plugins/gnome_screenshot.py", line 27, in grab
    im = read_prog_img([PROGRAM, "-f"])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/pyscreenshot/tempexport.py", line 27, in read_prog_img
    im = read_func_img(run_prog)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/pyscreenshot/tempexport.py", line 15, in read_func_img
    func(filename, bbox)
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/pyscreenshot/tempexport.py", line 23, in run_prog
    p.call()
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/easyprocess/__init__.py", line 147, in call
    self.start().wait(timeout=timeout)
    ^^^^^^^^^^^^
  File "/home/martin/bin/NormCap/lib/python3.12/site-packages/easyprocess/__init__.py", line 186, in start
    raise EasyProcessError(self, "start error")
easyprocess.EasyProcessError: start error <EasyProcess cmd_param=['gnome-screenshot', '-f', '/tmp/pyscreenshotnmmrqxrd/screenshot.png'] cmd=['gnome-screenshot', '-f', '/tmp/pyscreenshotnmmrqxrd/screenshot.png'] oserror=[Errno 2] No such file or directory: 'gnome-screenshot' return_code=None stdout="None" stderr="None" timeout_happened=False>
`

**Comment by M4rt1n12** [comment]
With flatpak it works!

**Comment by Daniel-Khodabakhsh** [comment]
I had a similar issue with a different AppImage. My fix was to extract the appimage with `app.AppImage --appimage-extract` then deleting the libwayland-client.so file, in my case it was `rm squashfs-root/libwayland-client.so.0`. Make sure you have your system's libwayland-client.so available in /lib or equivalent
