### ISSUE TITLE
SEGV after selection of screen rectangle

### ISSUE THREAD

**Issue by yurivict** [dynobo/normcap#672]
### What happened?

Once the rectangle is selected - the application crashes with this stack:
```
#0  0x0000000030f543b1 in QWidget::testAttribute_helper(Qt::WidgetAttribute) const () at /usr/local/lib/qt6/libQt6Widgets.so.6
#1  0x0000000030f0136b in QApplication::notify(QObject*, QEvent*) () at /usr/local/lib/qt6/libQt6Widgets.so.6
#2  0x000000002f51f644 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/local/lib/qt6/libQt6Core.so.6
#3  0x0000000030eff4e0 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
    at /usr/local/lib/qt6/libQt6Widgets.so.6
#4  0x0000000030f688b5 in ??? () at /usr/local/lib/qt6/libQt6Widgets.so.6
#5  0x0000000030f67a39 in ??? () at /usr/local/lib/qt6/libQt6Widgets.so.6
#6  0x0000000030efee88 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/local/lib/qt6/libQt6Widgets.so.6
#7  0x0000000030effdd9 in QApplication::notify(QObject*, QEvent*) () at /usr/local/lib/qt6/libQt6Widgets.so.6
#8  0x000000002f51f644 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/local/lib/qt6/libQt6Core.so.6
#9  0x00000000317192b8 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/local/lib/qt6/libQt6Gui.so.6
#10 0x000000003177a86b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/local/lib/qt6/libQt6Gui.so.6
#11 0x0000000033655a4f in ??? () at /usr/local/lib/qt6/plugins/platforms/../..//libQt6XcbQpa.so.6
#12 0x000000002eb91f71 in ??? () at /usr/local/lib/libglib-2.0.so.0
#13 0x000000002eb9231f in ??? () at /usr/local/lib/libglib-2.0.so.0
#14 0x000000002eb923b6 in g_main_context_iteration () at /usr/local/lib/libglib-2.0.so.0
#15 0x000000002f78bcee in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/local/lib/qt6/libQt6Core.so.6
#16 0x000000002f528af7 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/local/lib/qt6/libQt6Core.so.6
#17 0x000000002f51fe34 in QCoreApplication::exec() () at /usr/local/lib/qt6/libQt6Core.so.6
```

Versions: 0.5.8, 0.5.9
Python 3.11
py311-pyside6-6.7.3
clang-18
FreeBSD 14.1

### How did you install NormCap?

Unknown

### Operating System + Version?

FreeBSD 14.1

### Debug log output?*

```shell
n/a
```

**Comment by dynobo** [comment]
Seems like a duplicate of #658.
Feel free to re-open, if you think that's not the case.
