### ISSUE TITLE
Crash on Wayland, XGetImage failed

### ISSUE THREAD

**Issue by Igetin** [dynobo/normcap#76]
NormCap crashes when trying to run it under Wayland:

```
20:29:41 - INFO - normcap.normcap - Starting NormCap v0.1.2 ...
Traceback (most recent call last):
  File "/home/ige/.local/bin/normcap", line 10, in <module>
    sys.exit(run())
  File "/home/ige/.local/lib/python3.7/site-packages/normcap/__main__.py", line 5, in run
    _ = main()
  File "/home/ige/.local/lib/python3.7/site-packages/normcap/normcap.py", line 153, in main
    normcap_data = client_code(capture, normcap_data)
  File "/home/ige/.local/lib/python3.7/site-packages/normcap/normcap.py", line 106, in client_code
    result = handler.handle(normcap_data)
  File "/home/ige/.local/lib/python3.7/site-packages/normcap/handlers/capture_handler.py", line 26, in handle
    request = self._take_screeshot(request)
  File "/home/ige/.local/lib/python3.7/site-packages/normcap/handlers/capture_handler.py", line 40, in _take_screeshot
    raw = sct.grab(position)
  File "/home/ige/.local/lib/python3.7/site-packages/mss/linux.py", line 403, in grab
    ZPIXMAP,
  File "/home/ige/.local/lib/python3.7/site-packages/mss/linux.py", line 175, in validate
    raise ScreenShotError(err, details=details)
mss.exception.ScreenShotError: XGetImage() failed
```

**Comment by dynobo** [comment]
Thanks for the report, @Igetin . I can reproduce the problem on Ubuntu 20.04 with Gnome under Wayland.

This is probably an issue in the python library [mss](https://github.com/BoboTiG/python-mss), which I'm leveraging to get the screenshot on the multiple platform.

**Just to be sure, can you please also run the following snippet, e.g. by typing it in python3 console, can you confirm that you experience the same behavior as described below?**

If I run only the following lines...

```python
import mss
fn = mss.mss().shot(mon=-1, output="screenshot.png")
print(fn)
```
...under X it works (filename is printed, screenshot saved), while under Wayland I get the following error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/holger/.local/lib/python3.8/site-packages/mss/factory.py", line 41, in mss
    return linux.MSS(**kwargs)
  File "/home/holger/.local/lib/python3.8/site-packages/mss/linux.py", line 226, in __init__
    self.root = self.xlib.XDefaultRootWindow(MSS.display)
  File "/home/holger/.local/lib/python3.8/site-packages/mss/linux.py", line 175, in validate
    raise ScreenShotError(err, details=details)
mss.exception.ScreenShotError: XDefaultRootWindow() failed
```

**Comment by dynobo** [comment]
I opened an issue for `mss`: https://github.com/BoboTiG/python-mss/issues/155

Beside waiting to get this fix there, I'll think about a (temporary) workaround, e.g. by falling back to `pyscreenshot` or an execution of `gnome-screenshot`. But I'll have to check, how if the effort is worth the temporary benefit. Stay tuned! :-)

**Comment by dynobo** [comment]
I added a fallback for wayland. However, that workaround uses `gnome-screenshot` tool, which have to be installed (it is by default on Ubuntu). Please test and report back, if it worked.

**Comment by Igetin** [comment]
Works with the `gnome-screenshot` workaround, thank you.
